[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Optional: Redirect root to index.html
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200